
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.moretv.cn/whaley-vr-ios-lib/WVRPodSpecs.git'
platform :ios, "9.0"


target 'WVRBI' do
    
    pod 'UMengAnalytics-NO-IDFA'
    pod 'YYModel'
    pod 'WVRCache'
    pod 'WVRAppContext'

end

